apiVersion: v1
kind: Service
metadata:
  name: loggen
  namespace: application
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: loggen
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggen
  namespace: application
  labels:
    app: loggen
spec:
  replicas: {{REPLICAS}}
  selector:
    matchLabels:
      app: loggen
  template:
    metadata:
      labels:
        app: loggen
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: loggen
          image: "{{IMAGE_NAME}}:{{IMAGE_TAG}}"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          command:
            - ./loggen
            - server
