// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils(in *jlexer.Lexer, out *unprocessableEntityResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "errors":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Errors = make(map[string]unprocessableEntityError)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 unprocessableEntityError
					(v1).UnmarshalEasyJSON(in)
					(out.Errors)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils(out *jwriter.Writer, in unprocessableEntityResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"errors\":"
		out.RawString(prefix[1:])
		if in.Errors == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.Errors {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				(v2Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v unprocessableEntityResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v unprocessableEntityResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *unprocessableEntityResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *unprocessableEntityResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils(l, v)
}
func easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils1(in *jlexer.Lexer, out *unprocessableEntityError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "validator":
			out.Validator = string(in.String())
		case "value":
			out.Value = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils1(out *jwriter.Writer, in unprocessableEntityError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"validator\":"
		out.RawString(prefix[1:])
		out.String(string(in.Validator))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v unprocessableEntityError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v unprocessableEntityError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson79a3de99EncodeGithubComGigapipehqLoggenWebUtils1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *unprocessableEntityError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *unprocessableEntityError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson79a3de99DecodeGithubComGigapipehqLoggenWebUtils1(l, v)
}
