name: Build-n-Release

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Build
      run: go build -a -tags static -ldflags '-extldflags "-static"' -o loggen main.go
        
    - name: Strip & Compress
      run: |
        strip loggen
        upx loggen
        
    - name: Get Timestamp
      if: github.event_name != 'pull_request'
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
        
    - run: |
        echo "TIME=${{ steps.time.outputs.time }}" >> $GITHUB_ENV
    
    - name: Upload release
      if: github.event_name != 'pull_request'
      uses: boxpositron/upload-multiple-releases@1.0.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_config: |
            loggen
        tag_name: ${{ env.TIME }}
        release_name: loggen_${{ env.TIME }}
        draft: false
        prerelease: false
        overwrite: true   
        
